package com.chenyou.mapper;

import com.chenyou.pojo.BizGame;
import com.chenyou.pojo.BizGameExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizGameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_game
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int countByExample(BizGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_game
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int deleteByExample(BizGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_game
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_game
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int insert(BizGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_game
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int insertSelective(BizGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_game
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    List<BizGame> selectByExample(BizGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_game
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    BizGame selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_game
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") BizGame record, @Param("example") BizGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_game
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int updateByExample(@Param("record") BizGame record, @Param("example") BizGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_game
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int updateByPrimaryKeySelective(BizGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_game
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int updateByPrimaryKey(BizGame record);


    BizGame checkCodeUnique(String code);

    BizGame checkNameUnique(String name);

    List<BizGame> findAllByTime(@Param("time") Date time,@Param("temp") String temp);

    List<BizGame> findAllByTimeTo(@Param("start")Date start,@Param("end")Date end ,@Param("temp") String temp);
}