package com.chenyou.mapper;

import com.chenyou.pojo.CrmAccount;
import com.chenyou.pojo.CrmAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrmAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int countByExample(CrmAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int deleteByExample(CrmAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int insert(CrmAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int insertSelective(CrmAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    List<CrmAccount> selectByExample(CrmAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    CrmAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") CrmAccount record, @Param("example") CrmAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int updateByExample(@Param("record") CrmAccount record, @Param("example") CrmAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int updateByPrimaryKeySelective(CrmAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_account
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    int updateByPrimaryKey(CrmAccount record);

    CrmAccount getCrmAccount(String loginName);
}