package com.chenyou.mapper;

import com.chenyou.pojo.GameSubContract;
import com.chenyou.pojo.GameSubContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameSubContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Thu Nov 22 20:36:59 CST 2018
     */
    int countByExample(GameSubContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Thu Nov 22 20:36:59 CST 2018
     */
    int deleteByExample(GameSubContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Thu Nov 22 20:36:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Thu Nov 22 20:36:59 CST 2018
     */
    int insert(GameSubContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Thu Nov 22 20:36:59 CST 2018
     */
    int insertSelective(GameSubContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Thu Nov 22 20:36:59 CST 2018
     */
    List<GameSubContract> selectByExample(GameSubContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Thu Nov 22 20:36:59 CST 2018
     */
    GameSubContract selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Thu Nov 22 20:36:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameSubContract record, @Param("example") GameSubContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Thu Nov 22 20:36:59 CST 2018
     */
    int updateByExample(@Param("record") GameSubContract record, @Param("example") GameSubContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Thu Nov 22 20:36:59 CST 2018
     */
    int updateByPrimaryKeySelective(GameSubContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Thu Nov 22 20:36:59 CST 2018
     */
    int updateByPrimaryKey(GameSubContract record);
}