package com.chenyou.mapper;

import com.chenyou.pojo.GameSubContract;
import com.chenyou.pojo.GameSubContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface GameSubContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Fri Nov 23 15:58:08 CST 2018
     */
    int countByExample(GameSubContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Fri Nov 23 15:58:08 CST 2018
     */
    int deleteByExample(GameSubContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Fri Nov 23 15:58:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Fri Nov 23 15:58:08 CST 2018
     */
    int insert(GameSubContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Fri Nov 23 15:58:08 CST 2018
     */
    int insertSelective(GameSubContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Fri Nov 23 15:58:08 CST 2018
     */
    List<GameSubContract> selectByExample(GameSubContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Fri Nov 23 15:58:08 CST 2018
     */
    GameSubContract selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Fri Nov 23 15:58:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameSubContract record, @Param("example") GameSubContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Fri Nov 23 15:58:08 CST 2018
     */
    int updateByExample(@Param("record") GameSubContract record, @Param("example") GameSubContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Fri Nov 23 15:58:08 CST 2018
     */
    int updateByPrimaryKeySelective(GameSubContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_game_subcontract
     *
     * @mbggenerated Fri Nov 23 15:58:08 CST 2018
     */
    int updateByPrimaryKey(GameSubContract record);

    /*
    *
    * 管理员查询时间
    * @author hlx
    * @date 2018\11\23 0023 17:24
    * @param [start]
    * @return java.util.List<com.chenyou.pojo.GameSubContract>
    */
    List<GameSubContract> findListGameSubByTime(@Param("start")String start);

    /*
    *
    * 管理员查询开始和结束时间
    * @author hlx
    * @date 2018\11\23 0023 17:24
    * @param [start, end]
    * @return java.util.List<com.chenyou.pojo.GameSubContract>
    */
    List<GameSubContract> findListGameSubByTimes(@Param("start")String start, @Param("end")String end);

    /*
    *
    * 其它账户
    * @author hlx
    * @date 2018\11\23 0023 17:29
    * @param [channelId, start]
    * @return java.util.List<com.chenyou.pojo.GameSubContract>
    */
    List<GameSubContract> findListGameSubByTimeAndChannelId(@Param("channelId")String channelId,@Param("start")String start);


    /*
    *
    * 其它账户
    * @author hlx
    * @date 2018\11\23 0023 17:29
    * @param [channelId, start, end]
    * @return java.util.List<com.chenyou.pojo.GameSubContract>
    */
    List<GameSubContract> findListGameSubByTimesAndChannelId(@Param("channelId")String channelId,@Param("start")String start,@Param("end")String end);

}