package com.chenyou.pojo;

import java.util.Date;

public class CrmAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_account.id
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_account.name
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_account.login_name
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_account.salt
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_account.password
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_account.enable
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_account.created
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_account.modified
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_account.id
     *
     * @return the value of crm_account.id
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_account.id
     *
     * @param id the value for crm_account.id
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_account.name
     *
     * @return the value of crm_account.name
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_account.name
     *
     * @param name the value for crm_account.name
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_account.login_name
     *
     * @return the value of crm_account.login_name
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_account.login_name
     *
     * @param loginName the value for crm_account.login_name
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_account.salt
     *
     * @return the value of crm_account.salt
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_account.salt
     *
     * @param salt the value for crm_account.salt
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_account.password
     *
     * @return the value of crm_account.password
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_account.password
     *
     * @param password the value for crm_account.password
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_account.enable
     *
     * @return the value of crm_account.enable
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_account.enable
     *
     * @param enable the value for crm_account.enable
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_account.created
     *
     * @return the value of crm_account.created
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_account.created
     *
     * @param created the value for crm_account.created
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_account.modified
     *
     * @return the value of crm_account.modified
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_account.modified
     *
     * @param modified the value for crm_account.modified
     *
     * @mbggenerated Thu Nov 22 14:14:24 CST 2018
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}